<?php

use Faker\Generator as Faker;

/* @var Illuminate\Database\Eloquent\Factory $factory */

$factory->define(App\Assessment::class, function (Faker $faker) {
    return [
      'student_name' => $faker->words(2, true),
      'date' => $faker->date($format = 'Y-m-d', $max = 'now'),
      'start_time' => $faker->numberBetween($min = 1000, $max = 9999),
      'end_time' => $faker->numberBetween($min = 1000, $max = 9999),
      'medical_record_number' => function() {
          return factory(App\Patient::class)->create()->medical_record_number;
      },
      'reason' => $faker->sentence,
      'temperature' => $faker->randomFloat(2, 0, 999),
      'bp_over' => $faker->randomNumber,
      'bp_under' => $faker->randomNumber,
      'apical_pulse' => $faker->randomNumber,
      'respiration' => $faker->randomNumber,
      'oximetry' => $faker->randomNumber,
      'automatic' => $faker->boolean,
      'allergies' => $faker->word,
      'loc' => $faker->word,
      'orientation' => $faker->word,
      'speech' => $faker->word,
      'behavior' => $faker->word,
      'memory' => $faker->word,
      'pupillary' => $faker->word,
      'pupil_size' => $faker->randomNumber,
      'pupil_shape' => $faker->word,
      'accommodation' => $faker->word,
      'pain_scale' => $faker->randomNumber,
      'pain_location' => $faker->word,
      'skincolor' => $faker->word,
      'skintemp' => $faker->words(2, true),
      'hydration' => $faker->words(2, true),
      'integrity' => $faker->word,
      'dressings' => $faker->sentence,
      'ivsite' => $faker->sentence,
      'centrallines' => $faker->sentence,
      'heartrhythm' => $faker->word,
      'radial' => $faker->words(2, true),
      'capillary' => $faker->word,
      'right_upper' => $faker->words(2, true),
      'left_upper' => $faker->words(2, true),
      'right_breath' => $faker->word,
      'left_breath' => $faker->word,
      'cough' => $faker->word,
      'secretions' => $faker->word,
      'supplemental' => $faker->word,
      'diet' => $faker->word,
      'abdomen' => $faker->word,
      'bowel' => $faker->words(3, true),
      'stool' => $faker->sentence,
      'tubefeeding' => $faker->sentence,
      'genitourinary' => $faker->word,
      'urine' => $faker->word,
      'motion' => $faker->word,
      'muscle' => $faker->words(3, true),
      'right_pedal' => $faker->randomNumber,
      'left_pedal' => $faker->randomNumber,
      'right_lower' => $faker->words(2, true),
      'left_lower' => $faker->words(2, true),
      'peripheral' => $faker->sentence,
      'calf' => $faker->word,
      'ted' => $faker->word,
      'drainage' => $faker->word,
      'activity' => $faker->words(4, true),
    ];
});
