<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    /**
     * Escapes special characters in names generated by faker, such as single
     * quotes.
     *
     * @param string $str the string to escape
     * @return string the string with special characters escaped
     */
    protected function faker_escape($str)
    {
        return htmlspecialchars($str, ENT_HTML401 | ENT_QUOTES);
    }
}
